services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django:
    image: kojamad28/postgres-django-dev
    container_name: django
    build: 
      context: .
      args:
        REQ_DIR: "requirements/"
        REQ_TXT: "dev.txt"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src
    expose:
      - "8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  nginx:
    image: kojamad28/django-nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./static:/usr/src/static
      - ./media:/usr/src/media
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
